/**
 * esbuild configuration for the Jira Tiles plugin.
 *
 * Three modes are supported via CLI flags:
 *   --watch       Rebuild plugin (src/main.ts -> main.js) on file changes.
 *                 Used while developing inside an Obsidian vault.
 *   --serve       Spin up the dev preview harness (dev/harness.ts) and serve
 *                 dev/index.html on a free local port. File-watches fixtures
 *                 and source so the browser auto-reloads.
 *   --production  One-shot minified plugin build for distribution.
 *
 * The plugin bundle is consumed by Obsidian, which provides "obsidian" and
 * Electron's CommonJS modules at runtime — they are marked external so esbuild
 * does not try to inline them.
 */

import esbuild from "esbuild";
import process from "node:process";
import { builtinModules } from "node:module";
import { promises as fs } from "node:fs";
import path from "node:path";
import http from "node:http";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE.
If you want to view the source, visit the plugin's GitHub repository.
*/
`;

const args = new Set(process.argv.slice(2));
const isProduction = args.has("--production");
const isWatch = args.has("--watch");
const isServe = args.has("--serve");

// Modules supplied by Obsidian / Electron at runtime — never bundle them.
const externalModules = [
  "obsidian",
  "electron",
  "@codemirror/autocomplete",
  "@codemirror/collab",
  "@codemirror/commands",
  "@codemirror/language",
  "@codemirror/lint",
  "@codemirror/search",
  "@codemirror/state",
  "@codemirror/view",
  "@lezer/common",
  "@lezer/highlight",
  "@lezer/lr",
  ...builtinModules,
  ...builtinModules.map((m) => `node:${m}`),
];

/* -------------------------------------------------------------------------- */
/* Plugin build                                                               */
/* -------------------------------------------------------------------------- */

const pluginBuildOptions = {
  banner: { js: banner },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: externalModules,
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: isProduction ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
  minify: isProduction,
};

/* -------------------------------------------------------------------------- */
/* Dev preview build                                                          */
/* -------------------------------------------------------------------------- */

const devOutDir = path.join(__dirname, "dev", "dist");

const devBuildOptions = {
  entryPoints: ["dev/harness.ts"],
  bundle: true,
  format: "iife",
  target: "es2018",
  logLevel: "info",
  sourcemap: "inline",
  outfile: path.join(devOutDir, "harness.js"),
  // The harness runs in the browser; it imports from src/* (renderer, formatters).
  // The Obsidian shim (dev/obsidian-shim.ts) replaces the "obsidian" import via
  // an alias plugin so the renderer can run without the real Obsidian runtime.
  plugins: [
    {
      name: "obsidian-shim",
      setup(build) {
        build.onResolve({ filter: /^obsidian$/ }, () => ({
          path: path.join(__dirname, "dev", "obsidian-shim.ts"),
        }));
      },
    },
  ],
  loader: { ".css": "text" },
};

/* -------------------------------------------------------------------------- */
/* Helpers                                                                    */
/* -------------------------------------------------------------------------- */

/**
 * Copy the static dev assets (index.html, fixtures, css, plugin styles) into
 * the dev/dist directory so the dev server can serve them alongside the
 * compiled harness.js.
 */
async function copyDevAssets() {
  await fs.mkdir(devOutDir, { recursive: true });
  await fs.copyFile(
    path.join(__dirname, "dev", "index.html"),
    path.join(devOutDir, "index.html"),
  );
  await fs.copyFile(
    path.join(__dirname, "dev", "styles-dev.css"),
    path.join(devOutDir, "styles-dev.css"),
  );
  await fs.copyFile(
    path.join(__dirname, "styles.css"),
    path.join(devOutDir, "styles.css"),
  );
  // Copy fixtures wholesale.
  const fixturesSrc = path.join(__dirname, "dev", "fixtures");
  const fixturesDst = path.join(devOutDir, "fixtures");
  await fs.mkdir(fixturesDst, { recursive: true });
  const entries = await fs.readdir(fixturesSrc);
  for (const entry of entries) {
    await fs.copyFile(
      path.join(fixturesSrc, entry),
      path.join(fixturesDst, entry),
    );
  }
  // Generate a manifest of available fixtures so the harness can populate its
  // dropdown without listing the directory at runtime.
  const fixtureManifest = entries
    .filter((f) => f.endsWith(".json"))
    .map((f) => f.replace(/\.json$/, ""));
  await fs.writeFile(
    path.join(fixturesDst, "_index.json"),
    JSON.stringify(fixtureManifest, null, 2),
  );
}

/* -------------------------------------------------------------------------- */
/* Entry                                                                      */
/* -------------------------------------------------------------------------- */

async function run() {
  if (isServe) {
    await copyDevAssets();
    const ctx = await esbuild.context(devBuildOptions);
    // host: 127.0.0.1, port: 0 -> esbuild picks a free port.
    const { host, port } = await ctx.serve({
      servedir: devOutDir,
      host: "127.0.0.1",
      port: 0,
    });
    await ctx.watch();

    // Watch fixtures + plugin styles so changes trigger a rebuild copy.
    const watchPaths = [
      path.join(__dirname, "dev", "index.html"),
      path.join(__dirname, "dev", "styles-dev.css"),
      path.join(__dirname, "dev", "fixtures"),
      path.join(__dirname, "styles.css"),
    ];
    for (const p of watchPaths) {
      try {
        const watcher = (await import("node:fs")).watch(
          p,
          { recursive: true },
          async () => {
            try {
              await copyDevAssets();
            } catch (err) {
              console.error("[dev] asset copy failed:", err);
            }
          },
        );
        // Detach so the process can exit cleanly.
        watcher.unref?.();
      } catch {
        // Some paths may not exist yet; ignore.
      }
    }

    const url = `http://${host}:${port}/`;
    console.log("\n  Jira Tiles dev preview running at:\n  " + url + "\n");

    // Best-effort browser open (macOS / Linux / Windows).
    const opener = {
      darwin: ["open", url],
      linux: ["xdg-open", url],
      win32: ["cmd", "/c", "start", url],
    }[process.platform];
    if (opener) {
      const { spawn } = await import("node:child_process");
      try {
        spawn(opener[0], opener.slice(1), { stdio: "ignore", detached: true })
          .unref();
      } catch {
        // ignore
      }
    }
    return;
  }

  if (isWatch) {
    const ctx = await esbuild.context(pluginBuildOptions);
    await ctx.watch();
    console.log("[esbuild] watching plugin source...");
    return;
  }

  // One-shot build (production or default).
  await esbuild.build(pluginBuildOptions);
  console.log("[esbuild] plugin build complete.");
}

run().catch((err) => {
  console.error(err);
  process.exit(1);
});
