/**
 * esbuild configuration for the Jira Tiles plugin.
 *
 * Two modes are supported via CLI flags:
 *   --watch       Rebuild plugin (src/main.ts -> main.js) on file changes.
 *                 Used while developing inside an Obsidian vault.
 *   --production  One-shot minified plugin build for distribution.
 *
 * The browser-based dev preview harness lives on the `dev` branch (it is not
 * part of the published plugin and does not run inside Obsidian).
 *
 * The plugin bundle is consumed by Obsidian, which provides "obsidian" and
 * Electron's CommonJS modules at runtime — they are marked external so esbuild
 * does not try to inline them.
 */

import esbuild from "esbuild";
import process from "node:process";
import { builtinModules } from "node:module";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE.
If you want to view the source, visit the plugin's GitHub repository.
*/
`;

const args = new Set(process.argv.slice(2));
const isProduction = args.has("--production");
const isWatch = args.has("--watch");

// Modules supplied by Obsidian / Electron at runtime — never bundle them.
const externalModules = [
  "obsidian",
  "electron",
  "@codemirror/autocomplete",
  "@codemirror/collab",
  "@codemirror/commands",
  "@codemirror/language",
  "@codemirror/lint",
  "@codemirror/search",
  "@codemirror/state",
  "@codemirror/view",
  "@lezer/common",
  "@lezer/highlight",
  "@lezer/lr",
  ...builtinModules,
  ...builtinModules.map((m) => `node:${m}`),
];

/* -------------------------------------------------------------------------- */
/* Plugin build                                                               */
/* -------------------------------------------------------------------------- */

const pluginBuildOptions = {
  banner: { js: banner },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: externalModules,
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: isProduction ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
  minify: isProduction,
};

/* -------------------------------------------------------------------------- */
/* Entry                                                                      */
/* -------------------------------------------------------------------------- */

async function run() {
  if (isWatch) {
    const ctx = await esbuild.context(pluginBuildOptions);
    await ctx.watch();
    console.log("[esbuild] watching plugin source...");
    return;
  }

  // One-shot build (production or default).
  await esbuild.build(pluginBuildOptions);
  console.log("[esbuild] plugin build complete.");
}

run().catch((err) => {
  console.error(err);
  process.exit(1);
});
